version: '2.1'

services:
  tp:
    build:
      context: .
      dockerfile: ./processor/Dockerfile
    image: supply-tp
    container_name: processor
    volumes:
      - '.:/project/sawtooth-supply'

    command: |
      bash -c "
        ls -lai
        sleep 1
        cd processor
        python3 main.py -v -C tcp://validator:4004"
  rest_api:
    build:
      context: .
      dockerfile: ./rest_api/Dockerfile
    image: rest-api
    container_name: restapi
    volumes:
      - .:/project/sawtooth-supply
    ports:
      - '8080:8080'

    command: |
      bash -c "
        ls -lai
        cd rest_api
        python3 main.py \
          -B rest_api:8080 \
          -C validator:4004\
          --db-host postgres \
          -vv"
  simple-supply-shell:
    build:
      context: .
      dockerfile: ./shell/Dockerfile
    image: sawtooth-simple-supply-shell
    container_name: simple-supply-shell
    volumes:
      - .:/project/sawtooth-simple-supply
    command: |
      bash -c "
        simple-supply-protogen
      "
  simple-supply-subscriber:
    build:
      context: .
      dockerfile: ./subscriber/Dockerfile
    image: sawtooth-simple-supply-subscriber
    container_name: simple-supply-subscriber
    volumes:
      - '.:/project/sawtooth-simple-supply'
    depends_on:
      - simple-supply-shell
      - postgres
    command: |
      bash -c "
        simple-supply-subscriber init \
          --db-host postgres \
          -vv
        sleep 3
        simple-supply-subscriber subscribe \
          --db-host postgres \
          -C tcp://validator:4004 \
          -vv
      "

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: sawtooth-settings-tp-testapp
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  sawtooth:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: sawtooth-rest-api-testapp
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -vv -C tcp://validator:4004 --bind sawtooth:8008

  validator:
    image: hyperledger/sawtooth-validator:1.0
    container_name: sawtooth-validator-testapp
    expose:
      - 4004
    ports:
      - '4004:4004'
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          sawtooth keygen my_key
          sawset genesis -k /root/.sawtooth/keys/my_key.priv
          sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -vv \
          --endpoint tcp://localhost:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050"

  postgres:
    image: postgres:alpine
    container_name: simple-supply-postgres
    restart: always
    environment:
      POSTGRES_USER: sawtooth
      POSTGRES_PASSWORD: sawtooth
      POSTGRES_DB: simple-supply
    ports:
      - '5432:5432'
