# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rpayload.proto\"\xbd\x02\n\rSupplyPayload\x12%\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x15.SupplyPayload.Action\x12(\n\x0c\x63reate_agent\x18\x02 \x01(\x0b\x32\x12.CreateAgentAction\x12&\n\x0b\x63reate_item\x18\x03 \x01(\x0b\x32\x11.CreateItemAction\x12&\n\x0bupdate_item\x18\x04 \x01(\x0b\x32\x11.UpdateItemAction\x12(\n\x0ctranfer_item\x18\x05 \x01(\x0b\x32\x12.TranferItemAction\x12\x11\n\ttimestamp\x18\x06 \x01(\x04\"N\n\x06\x41\x63tion\x12\x10\n\x0c\x43REATE_AGENT\x10\x00\x12\x0f\n\x0b\x43REATE_ITEM\x10\x01\x12\x0f\n\x0bUPDATE_ITEM\x10\x02\x12\x10\n\x0cTRANFER_ITEM\x10\x03\"/\n\x11\x43reateAgentAction\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\"H\n\x10\x43reateItemAction\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x04\x12\x11\n\tlongitude\x18\x03 \x01(\x04\"H\n\x10UpdateItemAction\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x04\x12\x11\n\tlongitude\x18\x03 \x01(\x04\"<\n\x11TranferItemAction\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x16\n\x0ereceived_agent\x18\x02 \x01(\tb\x06proto3')
)



_SUPPLYPAYLOAD_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='SupplyPayload.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CREATE_AGENT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE_ITEM', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE_ITEM', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANFER_ITEM', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=257,
  serialized_end=335,
)
_sym_db.RegisterEnumDescriptor(_SUPPLYPAYLOAD_ACTION)


_SUPPLYPAYLOAD = _descriptor.Descriptor(
  name='SupplyPayload',
  full_name='SupplyPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='SupplyPayload.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_agent', full_name='SupplyPayload.create_agent', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_item', full_name='SupplyPayload.create_item', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_item', full_name='SupplyPayload.update_item', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tranfer_item', full_name='SupplyPayload.tranfer_item', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='SupplyPayload.timestamp', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SUPPLYPAYLOAD_ACTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=335,
)


_CREATEAGENTACTION = _descriptor.Descriptor(
  name='CreateAgentAction',
  full_name='CreateAgentAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CreateAgentAction.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role', full_name='CreateAgentAction.role', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=384,
)


_CREATEITEMACTION = _descriptor.Descriptor(
  name='CreateItemAction',
  full_name='CreateItemAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='CreateItemAction.item_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='CreateItemAction.latitude', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='CreateItemAction.longitude', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=386,
  serialized_end=458,
)


_UPDATEITEMACTION = _descriptor.Descriptor(
  name='UpdateItemAction',
  full_name='UpdateItemAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='UpdateItemAction.item_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='UpdateItemAction.latitude', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='UpdateItemAction.longitude', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=460,
  serialized_end=532,
)


_TRANFERITEMACTION = _descriptor.Descriptor(
  name='TranferItemAction',
  full_name='TranferItemAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='TranferItemAction.item_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='received_agent', full_name='TranferItemAction.received_agent', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=534,
  serialized_end=594,
)

_SUPPLYPAYLOAD.fields_by_name['action'].enum_type = _SUPPLYPAYLOAD_ACTION
_SUPPLYPAYLOAD.fields_by_name['create_agent'].message_type = _CREATEAGENTACTION
_SUPPLYPAYLOAD.fields_by_name['create_item'].message_type = _CREATEITEMACTION
_SUPPLYPAYLOAD.fields_by_name['update_item'].message_type = _UPDATEITEMACTION
_SUPPLYPAYLOAD.fields_by_name['tranfer_item'].message_type = _TRANFERITEMACTION
_SUPPLYPAYLOAD_ACTION.containing_type = _SUPPLYPAYLOAD
DESCRIPTOR.message_types_by_name['SupplyPayload'] = _SUPPLYPAYLOAD
DESCRIPTOR.message_types_by_name['CreateAgentAction'] = _CREATEAGENTACTION
DESCRIPTOR.message_types_by_name['CreateItemAction'] = _CREATEITEMACTION
DESCRIPTOR.message_types_by_name['UpdateItemAction'] = _UPDATEITEMACTION
DESCRIPTOR.message_types_by_name['TranferItemAction'] = _TRANFERITEMACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SupplyPayload = _reflection.GeneratedProtocolMessageType('SupplyPayload', (_message.Message,), {
  'DESCRIPTOR' : _SUPPLYPAYLOAD,
  '__module__' : 'payload_pb2'
  # @@protoc_insertion_point(class_scope:SupplyPayload)
  })
_sym_db.RegisterMessage(SupplyPayload)

CreateAgentAction = _reflection.GeneratedProtocolMessageType('CreateAgentAction', (_message.Message,), {
  'DESCRIPTOR' : _CREATEAGENTACTION,
  '__module__' : 'payload_pb2'
  # @@protoc_insertion_point(class_scope:CreateAgentAction)
  })
_sym_db.RegisterMessage(CreateAgentAction)

CreateItemAction = _reflection.GeneratedProtocolMessageType('CreateItemAction', (_message.Message,), {
  'DESCRIPTOR' : _CREATEITEMACTION,
  '__module__' : 'payload_pb2'
  # @@protoc_insertion_point(class_scope:CreateItemAction)
  })
_sym_db.RegisterMessage(CreateItemAction)

UpdateItemAction = _reflection.GeneratedProtocolMessageType('UpdateItemAction', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEITEMACTION,
  '__module__' : 'payload_pb2'
  # @@protoc_insertion_point(class_scope:UpdateItemAction)
  })
_sym_db.RegisterMessage(UpdateItemAction)

TranferItemAction = _reflection.GeneratedProtocolMessageType('TranferItemAction', (_message.Message,), {
  'DESCRIPTOR' : _TRANFERITEMACTION,
  '__module__' : 'payload_pb2'
  # @@protoc_insertion_point(class_scope:TranferItemAction)
  })
_sym_db.RegisterMessage(TranferItemAction)


# @@protoc_insertion_point(module_scope)
